services:
  openmina_node:
    build:
      context: ./
      dockerfile: Dockerfile
    command: [ "node" ]
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile_FE
      args:
        BUILD_CONFIGURATION: local
    ports:
      - "8070:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge