services:
  openmina-node:
    image: openmina/openmina:${OPENMINA_TAG:-latest}
    entrypoint: >
      sh -c "openmina node $${OPENMINA_LIBP2P_EXTERNAL_IP:+--libp2p-external-ip $$OPENMINA_LIBP2P_EXTERNAL_IP}"
    volumes:
      - ./openmina-workdir:/root/.openmina:rw
    ports:
      - "3000:3000"
      - "8302:8302"
    environment:
      OPENMINA_LIBP2P_EXTERNAL_IP: "${OPENMINA_LIBP2P_EXTERNAL_IP}"

  frontend:
    image: openmina/frontend:${OPENMINA_FRONTEND_TAG:-latest}
    environment:
      OPENMINA_FRONTEND_ENVIRONMENT: compose
    ports:
      - "8070:80"
