services:
  openmina-node:
    image: openmina/openmina:${OPENMINA_TAG:-latest}
    command: [ "node" ]
    ports:
      - "3000:3000"
      - "8302:8302"

  frontend:
    image: openmina/frontend:${OPENMINA_FRONTEND_TAG:-latest}
    environment:
      OPENMINA_FRONTEND_ENVIRONMENT: compose
    ports:
      - "8070:80"
